# Generated by Django 3.1.1 on 2020-09-29 04:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200929_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/users/person_1.jpg', upload_to='media/users'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
